### ISSUE TITLE
Lovely Appearing Mod For Information Availability But Making it More Game Practical? 

### ISSUE THREAD

**Issue by FriendlyGamer** [nixnoxus/moreinfo#1]
Hiya! I run an accessibly minded survival server and as such I took interest in this mod, unfortunately it seems like as the CDB listing said (WIP) some refining is in order. 

Would it be possible to make the mod only shows information when it's relevant to do so? For example when players are getting into the direction of whatever it is (their bed, their bones, etc) and such? 

Cause as it stands, it definity takes too much screen space and I am not sure how to "optimize" this for typical game play even with the settingtypes.txt in mind.

**Comment by nixnoxus** [comment]
> Would it be possible to make the mod only shows information when it's relevant to do so? For example when players are getting into the direction of whatever it is (their bed, their bones, etc) and such?

the information block for the waypoints contains a direction indicator. this should help to find the waypoints, if this is not in the field of view. this is the reason why all waypoints are shown. 

> Cause as it stands, it definity takes too much screen space and I am not sure how to "optimize" this for typical game play even with the settingtypes.txt in mind.

yes, at first glance, the amount of information seems overwhelming. I still have to work on that.

in the default setting everything is activated to get an overview of the features.
Each information block can be deactivated:

- the defaults for all players by the admin in the minetest.conf:
```
moreinfo.display_waypoint_info = false
moreinfo.display_position_info = false
moreinfo.display_game_info = false
moreinfo.display_players_info = false
```
- or through chat commands by the player:
```
/moreinfo -waypoint
/moreinfo -position
/moreinfo -game
/moreinfo -players
``` 
the player can reactivate all information blocks with `/moreinfo +any`

I hope it helps. further ideas and suggestions are welcome.
